### ISSUE TITLE
I can not run Markov clustering (mcl) of hard clusters step

### ISSUE THREAD

**Issue by icruz1989** [ohdongha/CL_finder#2]
Dear ohdongha

I am triying to run the step number two in ONfinder (mcl). I think the code is not working well because when I run it, it seems to run well and after a while I get in my mcl directory an empty file 
This is the error
.................................................. 1M
.................................................. 2M
..............
  File "/home/icruz/data/CLfinder/OrthNet/scripts/parse_mclOutput.py", line 174
    for key, value in sorted(clusterID_dict.iteritems(), key=lambda (k, v): (v,k), reverse=False):
                                                                    ^
SyntaxError: invalid syntax
cat: ./mcl/02619_solana.list.0.mclOutput.parsed.txt: No such file or directory
  File "/home/icruz/data/CLfinder/OrthNet/scripts/parse_mclOutput.py", line 174
    for key, value in sorted(clusterID_dict.iteritems(), key=lambda (k, v): (v,k), reverse=False):

SyntaxError: invalid syntax
cat: ./mcl/02619_solana.list.2555.mclOutput.parsed.txt: No such file or directory
rm: cannot remove './mcl/02619_solana.list.*.mclOutput.parsed.txt': No such file or directory
done reading the edge weight matrix file weights4mcl_OrthNet.list
5517 mclInput files were created, out of 6514 total clusters
out of 6514 total clusters, 5517 were subjected to mcl, which further divided 675 clusters into 6884 sub-clusters.
cleaning temporary files
done

**Comment by ohdongha** [comment]
Hello Ivan, 
Can you give me the two command lines you used for running the `create_OrthNet.py` and `mcl_OrthNet.py`? 

(1) If you had run the second step with somthing like
`mcl_OrthNet.py  02619_solana.list -o mcl -sc -w weights4mcl.list -I 1.2`
can you try again with 
`mcl_OrthNet.py  02619_solana -o mcl -sc -w weights4mcl.list -I 1.2`
(i.e. using only the _ProjectID_, without the ".list" extension)?

(2) If (1) does not work, can you post first several lines of _ProjectID.4OrthNet.input_ (the input for `create_OrthNet.py`) and _ProjectID.clstrd.edges_ (the output of `create_OrthNet.py` and the input for `mcl_OrthNet.py`?

Thanks, 
Dong-Ha

**Comment by icruz1989** [comment]
Hello ohdongha, thank you for your answer

These were the command lines that I used to run orthnet:
`python2 ../../scripts/create_OrthNet.py 02619_solana.list -sd -i 02619_solana.4OrthNet.input -T .gtfParsed.TD.txt -o ./onfinder.out &`

`python2 ../../scripts/mcl_OrthNet.py 02619_solana.list -i /home/icruz/data/CLfinder/OrthNet/allgenomescorected/onfinder/onfinder.out/ -w weights4mcl_OrthNet.list -o ./mcl -sc -I 1.2 >& runmcl.orthet.out &`

I am watching that you did not specify in your example the input file for mcl_OrthNet.py? 

best regards

**Comment by ohdongha** [comment]
`mcl_OrthNet.py` will look for _ProjectID.clstrd.edges_ in the folder specified by '-i' (./onfinder.out) as input.  So in your case, it will try to use _./onfinder.out/02619_solana.list.clstrd.edges_, as the input file. 

I realized that the error happened when `mcl_OrthNet.py` called `parse_mclOutput.py`.  I am testing this script on a test dataset again.  

... (obsolete answers deleted) ...

EDIT2: Another possibility is that when `parse_mclOutput.py` was called within the `mcl_OrthNet.py`, it will use the default python interpreter (`/usr/bin/env python`).  If this default python interpreter is Python 3, I guess there will be this issue.  Let me check this possibility...

EDIT3: indeed, `parse_mclOutput.py` will give that Syntax error if run with python3.  I will check whether there is a way to temporarily set `/usr/bin/env python` to your `python2`.  

EDIT4: there is a workaround that seems working: 
```
mkdir ~/temp_bin
PATH=~/temp_bin:$PATH
ln -s /path_to_your_python2/python2 ~/temp_bin/python
```
This trick is from [this StackOverflow thread](https://stackoverflow.com/a/27453324/6283377).  To stop using python2 as the default python, simply exit and restart the terminal.

Will this work for you?

**Comment by icruz1989** [comment]
Hello Dr. ohdongha 

I already have followed your suggestions and I could run the script without problems and I have finished the tutorial. 

Now, I am going to take a look of the results and try to find an interesting thing.

**Comment by ohdongha** [comment]
Great.  Let me know if you have anything else and stay tuned for the update.  I will close this.
